# ============================================================
# NORMALISATION DICTIONARY — Hindi Fluency Experiment
# Maps every Roman word (transliterations, English, typos)
# to its canonical Devanagari form.
#
# None = noise word (adjective/non-food/unclear) → will be REMOVED
# ============================================================

NORM_DICT = {

    # ── ANIMALS ─────────────────────────────────────────────

    # English → Devanagari
    "tiger":        "बाघ",
    "lion":         "शेर",
    "cat":          "बिल्ली",
    "dog":          "कुत्ता",
    "deer":         "हिरण",
    "horse":        "घोड़ा",
    "cheetah":      "चीता",
    "fox":          "लोमड़ी",
    "cow":          "गाय",
    "goat":         "बकरी",
    "bear":         "भालू",
    "elephant":     "हाथी",
    "ox":           "बैल",
    "leopard":      "तेंदुआ",
    "giraffe":      "जिराफ",
    "parrot":       "तोता",
    "owl":          "उल्लू",
    "sheep":        "भेड़",
    "wolf":         "भेड़िया",
    "camel":        "ऊँट",
    "donkey":       "गधा",
    "buffalo":      "भैंस",
    "rabbit":       "खरगोश",
    "snake":        "साँप",
    "duck":         "बत्तख",
    "monkey":       "बंदर",
    "hen":          "मुर्गी",
    "hyena":        "लकड़बग्घा",
    "dolphin":      "डॉल्फिन",
    "whale":        "व्हेल",
    "shark":        "शार्क",
    "sparrow":      "गौरैया",
    "crow":         "कौआ",
    "eagle":        "बाज़",
    "peacock":      "मोर",
    "mice":         "चूहा",
    "mouse":        "चूहा",
    "rat":          "चूहा",
    "pig":          "सूअर",
    "chicken":      "मुर्गी",
    "gorilla":      "गोरिल्ला",
    "ant":          "चींटी",
    "jackal":       "गीदड़",
    "anaconda":     "एनाकोंडा",
    "python":       "अजगर",
    "penguin":      "पेंगुइन",
    "puma":         "प्यूमा",
    "zebra":        "ज़ेब्रा",

    # Transliterations → Devanagari
    "kutta":        "कुत्ता",
    "sher":         "शेर",
    "billi":        "बिल्ली",
    "ghoda":        "घोड़ा",
    "lomdi":        "लोमड़ी",
    "hathi":        "हाथी",
    "gadha":        "गधा",
    "chuha":        "चूहा",
    "bail":         "बैल",
    "bandar":       "बंदर",
    "gaay":         "गाय",
    "bakri":        "बकरी",
    "bakra":        "बकरा",
    "bhediya":      "भेड़िया",
    "suar":         "सूअर",
    "baagh":        "बाघ",
    "hiran":        "हिरण",
    "saap":         "साँप",
    "bhalu":        "भालू",
    "murgi":        "मुर्गी",
    "murga":        "मुर्गा",
    "batak":        "बत्तख",
    "magarmacch":   "मगरमच्छ",
    "kabootar":     "कबूतर",
    "langoor":      "लंगूर",
    "kacchhuaa":    "कछुआ",
    "oont":         "ऊँट",
    "bhed":         "भेड़",
    "pakshi":       "पक्षी",
    "moor":         "मोर",
    "mor":          "मोर",
    "machli":       "मछली",
    "khargosh":     "खरगोश",
    "cheenti":      "चींटी",
    "simh":         "सिंह",
    "gayan":        "गयाल",
    "geedad":       "गीदड़",

    # Spelling variants → Devanagari
    "cheeta":       "चीता",
    "leapord":      "तेंदुआ",
    "girrafe":      "जिराफ",
    "chuuha":       "चूहा",
    "haathi":       "हाथी",
    "gaai":         "गाय",
    "baag":         "बाघ",
    "bagh":         "बाघ",
    "buffaloe":     "भैंस",
    "bufflow":      "भैंस",
    "saanp":        "साँप",
    "bhaaloo":      "भालू",
    "bhaalu":       "भालू",
    "bhallu":       "भालू",
    "dolhin":       "डॉल्फिन",
    "saprrow":      "गौरैया",
    "peigien":      "कबूतर",
    "crcocdile":    "मगरमच्छ",
    "bhes":         "भैंस",
    "bhais":        "भैंस",
    "coe":          "गाय",       # typo for cow
    "billi'":       "बिल्ली",    # trailing apostrophe
    "what":         None,         # NOISE

    # ── BODY PARTS ──────────────────────────────────────────

    # Transliterations → Devanagari
    "pair":         "पैर",
    "naak":         "नाक",
    "baal":         "बाल",
    "kaan":         "कान",
    "aankh":        "आँख",
    "hath":         "हाथ",
    "pet":          "पेट",
    "peeth":        "पीठ",
    "ungli":        "उँगली",
    "jeebh":        "जीभ",
    "muh":          "मुँह",
    "sir":          "सिर",
    "gaal":         "गाल",
    "gala":         "गला",
    "dil":          "दिल",
    "dimag":        "दिमाग",
    "taang":        "टाँग",
    "daant":        "दाँत",
    "gardan":       "गर्दन",
    "ghutna":       "घुटना",
    "kohni":        "कोहनी",
    "chaati":       "छाती",
    "maatha":       "माथा",
    "baahu":        "बाहु",
    "chamdi":       "चमड़ी",
    "nakh":         "नाक",
    "khopdi":       "खोपड़ी",
    "pait":         "पेट",
    "fefde":        "फेफड़े",
    "gurde":        "गुर्दे",
    "hridai":       "हृदय",
    "maanspeshiya": "माँसपेशियाँ",
    "khoon":        "खून",
    "hadiyan":      "हड्डियाँ",

    # Spelling variants
    "haath":        "हाथ",
    "aanhkein":     "आँख",
    "aakhn":        "आँख",
    "ungliyan":     "उँगली",
    "jeeb":         "जीभ",
    "mu":           "मुँह",
    "sar":          "सिर",
    "daat":         "दाँत",

    # English → Devanagari
    "leg":          "टाँग",
    "head":         "सिर",
    "hands":        "हाथ",
    "toe":          "पैर की उँगली",
    "palm":         "हथेली",
    "knee":         "घुटना",
    "chin":         "ठुड्डी",
    "nose":         "नाक",
    "chest":        "छाती",
    "calf":         "पिंडली",
    "abdomen":      "पेट",
    "embow":        "कोहनी",    # typo for elbow
    "bicep":        "डोले",
    "tricep":       "ट्राइसेप",

    # ── COLOURS ─────────────────────────────────────────────

    # English → Devanagari
    "pink":         "गुलाबी",
    "red":          "लाल",
    "green":        "हरा",
    "orange":       "नारंगी",
    "white":        "सफेद",
    "black":        "काला",
    "blue":         "नीला",
    "yellow":       "पीला",
    "violet":       "बैंगनी",
    "brown":        "भूरा",
    "purple":       "बैंगनी",
    "grey":         "धूसर",
    "gray":         "धूसर",
    "golden":       "सुनहरा",
    "silver":       "चाँदी",
    "saffron":      "केसरिया",
    "azure":        "आसमानी",
    "sky blue":     "आसमानी",
    "olive green":  "जैतूनी",
    "neon green":   "हरा",
    "sapphire":     "नीला",
    "turquoise":    "फ़िरोज़ी",
    "indigo":       "इंडिगो",
    "maroon":       "मैरून",
    "cyan":         "सियान",
    "magenta":      "मैजेंटा",
    "navy":         "नेवी",
    "navy blue":    "नेवी",
    "royal blue":   "रॉयल ब्लू",
    "teal":         "टील",
    "cream":        "क्रीम",
    "biege":        "मटमैला",

    # Transliterations → Devanagari
    "peela":        "पीला",
    "kaala":        "काला",
    "hara":         "हरा",
    "neela":        "नीला",
    "safed":        "सफेद",
    "laal":         "लाल",
    "gulaabi":      "गुलाबी",
    "bhagwa":       "भगवा",
    "gerua":        "गेरुआ",
    "naarangi":     "नारंगी",
    "ferozi":       "फ़िरोज़ी",
    "rajat":        "रजत",
    "swarna":       "स्वर्ण",
    "kaansya":      "काँस्य",
    "bhoora":       "भूरा",
    "santara":      "नारंगी",   # santara = orange fruit → colour

    # Spelling variants
    "safid":        "सफेद",
    "lal":          "लाल",
    "gulabi":       "गुलाबी",
    "naaringe":     "नारंगी",
    "bhuura":       "भूरा",
    "hera":         "हरा",     

    # ── FOODS ───────────────────────────────────────────────

    # Transliterations → Devanagari
    "roti":         "रोटी",
    "chawal":       "चावल",
    "dal":          "दाल",
    "daal":         "दाल",
    "sabzi":        "सब्ज़ी",
    "dahi":         "दही",
    "idli":         "इडली",
    "bhindi":       "भिंडी",
    "dosa":         "डोसा",
    "vada":         "वड़ा",
    "kaddu":        "कद्दू",
    "urad":         "उड़द",
    "moong":        "मूँग",
    "rajma":        "राजमा",
    "arhar":        "अरहर",
    "masoor":       "मसूर",
    "doodh":        "दूध",
    "ghee":         "घी",
    "gajar":        "गाजर",
    "tamatar":      "टमाटर",
    "paneer":       "पनीर",
    "gehun":        "गेहूँ",
    "atta":         "आटा",
    "kachori":      "कचौरी",
    "halwa":        "हलवा",
    "pyaaz":        "प्याज",
    "chana":        "चना",
    "lauki":        "लौकी",
    "tinda":        "टिंडा",
    "sitaphal":     "सीताफल",
    "petha":        "पेठा",
    "macchi":       "मछली",
    "ande":         "अंडे",
    "paani":        "पानी",
    "lassi":        "लस्सी",
    "anaar":        "अनार",
    "karela":       "करेला",
    "khicdi":       "खिचड़ी",
    "chaat":        "चाट",
    "aloo":         "आलू",
    "matar":        "मटर",
    "palak":        "पालक",
    "gobi":         "गोभी",
    "chakli":       "चकली",
    "paratha":      "पराठा",
    "chapati":      "चपाती",
    "mirchi":       "मिर्ची",
    "baingan":      "बैंगन",
    "mausambi":     "मौसंबी",
    "seb":          "सेब",
    "sambar":       "साँभर",
    "chole":        "छोले",
    "fal":          "फल",
    "pani puri":    "पानी पूरी",
    "rasam":        "रसम",
    "murga":        "मुर्गा",
   "ladoon cake":  "लड्डू",

    # English → Devanagari
    "rice":         "चावल",
    "wheat":        "गेहूँ",
    "carrot":       "गाजर",
    "onion":        "प्याज",
    "chicken":      "मुर्गा",
    "peas":         "मटर",
    "potatoes":     "आलू",
    "milk":         "दूध",
    "curd":         "दही",
    "corn":         "मक्का",
    "cucumber":     "खीरा",
    "spinach":      "पालक",
    "radish":       "मूली",
    "cauliflower":  "फूलगोभी",
    "cabbage":      "पत्तागोभी",
    "grapes":       "अंगूर",
    "mango":        "आम",
    "apple":        "सेब",
    "banana":       "केला",
    "tomato":       "टमाटर",
    "brinjal":      "बैंगन",
    "sweets":       "मिठाई",
    "fruits":       "फल",
    "oil":          "तेल",
    "pulses":       "दाल",
    "pulse":        "दाल",
    "tea":          "चाय",
    

    # Spelling variants
    "chaval":       "चावल",
    "aata":         "आटा",
    "dooth":        "दूध",
    "dhudh":        "दूध",
    "aalu":         "आलू",
    "bataka":       "आलू",
    "baigan":       "बैंगन",
    "moong daal":   "मूँग दाल",
    "soya bean":    "सोयाबीन",
    "soyabean":     "सोयाबीन",
    "potatop":      "आलू",      # typo
    "samaso":       "समोसा",
    "samaosa":      "समोसा",
    "macroni":      "पास्ता",
    "coffe":        "कॉफ़ी",
    "suar (pork)":  "सूअर",
    "beef (buffalo)": "गोमांस",
    "mix veg":      "सब्ज़ी",
    "crispy veg":   "सब्ज़ी",
    "fried rice":   "चावल",
    "garlic bread": "ब्रेड",
    "paneer sizzler": "पनीर",
    "baby corn":    "मक्का",
    "chole bhautre": "छोले",
    "ladyfinger":   "भिंडी",
    "anteater":     "चींटीखोर",

    # Keep as-is (loanwords / brand names)
    "burger":       "बर्गर",
    "maggi":        "मैगी",
    "pizza":        "पिज्जा",
    "pasta":        "पास्ता",
    "bread":        "ब्रेड",
    "chocolate":    "चॉकलेट",
    "sandwich":     "सैंडविच",
    "pastry":       "पेस्ट्री",
    "chips":        "चिप्स",
    "noodles":      "नूडल्स",
    "ramen":        "रामेन",
    "cake":         "केक",
    "lays":         "लेज़",
    "mutton":       "मटन",
    "cold drinks":  "शीतल पेय",

    # NOISE — remove from analysis entirely
    "tiffins":      None,
    "dairy":        None,
    "swadisht":     None,
    "meetha":       None,
    "teekha":       None,
    "chatpata":     None,
    "bhukh":        None,
    "dawaaiya":     None,
    
}
